### ISSUE TITLE
Clicking on a city should change the URL

### ISSUE THREAD

**Issue by etelsv** [prisma/women-world-wide#1]
Currently when a user chooses to see the organizations in a specific city, there is no permanent URL that would allow them to return to that list. 

It would be great if the URL could change to match the selected location. For example, if a user wanted to see just the group in Paris, the URL would change to `https://womenworldwide.dev/paris` They could then link to that specific part of the site, etc

**Comment by leonardodino** [comment]
I can give this a try! (:

I think that `/france/paris` may be more future-proof / collision resistant.
the countries already have `slugs`, so it won't change data or anything.

any thoughts?
